// <auto-generated />
namespace MRS.Infrastructure.EFData.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CreateInitialTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateInitialTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201401100059107_CreateInitialTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
